name: Laravel

on:
  pull_request:
  push:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env
        run: cp src/.env.testing infra/scheduler/.env

      # Sobe os containers com o app e nginx
      - name: Build and start containers
        run: docker compose -f infra/scheduler/docker-compose.yml up -d

      # Instala dependÃªncias via composer dentro do container
      - name: Install Dependencies
        run: docker compose -f infra/scheduler/docker-compose.yml exec -T world-scraper composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: docker compose -f infra/scheduler/docker-compose.yml exec -T world-scraper chmod -R 777 storage bootstrap/cache

      - name: Create SqlLite database
        run: docker compose -f infra/scheduler/docker-compose.yml exec -T world-scraper touch database/database.sqlite

      - name: Generate App key
        run: docker compose -f infra/scheduler/docker-compose.yml exec -T world-scraper php artisan key:generate

      - name: Run Migrations
        run: docker compose -f infra/scheduler/docker-compose.yml exec -T world-scraper php artisan migrate --force

      - name: Run Seeders
        run: docker compose -f infra/scheduler/docker-compose.yml exec -T world-scraper php artisan db:seed

      - name: Run Tests with PHPUnit + Xdebug
        run: docker compose -f infra/scheduler/docker-compose.yml exec -T world-scraper vendor/bin/phpunit --colors=never